pub(crate) mod advect_painter;
pub(crate) mod blit_painter;
pub(crate) mod debug_painter;
mod distance_field_painter;
pub(crate) mod effect_painter;
pub(crate) mod gl_buffer;
pub(crate) mod gl_framebuffer;
pub(crate) mod gl_garbage;
pub(crate) mod gl_texture;
pub(crate) mod inflow_painter;
pub(crate) mod particle_painter;
pub(crate) mod shader;
pub(crate) mod simulation_painter;
pub(crate) mod smoothing_painter;
pub(crate) mod solid_painter;
mod utils;
pub(crate) mod water_painter;
